### PR TITLE
Add len() function to Mime

### PR DESCRIPTION
**Pull request by teotwaki**
As discussed in #2, here is the PR.

This PR adds `len()` functions to both Mime and FormatQuotedString. It also adds an `is_empty()` function to Mime as clippy was really nagging me to do so. I've made that a static `false` as I don't believe it is possible to construct an empty Mime object.

I've added unit tests for the len implementation in both Mime and FormatedQuotedString. I believe I've covered most cases, but please let me know if there's cases that should be extended.

### CODE REVIEW

**Review by notgull — APPROVED** [review]
Looks good to me!

By the way, may I ask what you're using `mr-mime` for? I originally wanted to use it to make an HTTP implementation, but I got distracted and never finished it.

Also, do you plan on adding anything else, or should I cut a release with just this?

**Comment by teotwaki** [comment]
Great!

As for my use-case: I'm building an industrial camera (bare-metal, no_std, with an alloc) which needs to communicate with an HTTP service. I'm writing my own multipart library (not published yet), and using `mr-mime` in it as I want to correctly handle the MIME types. In my specific case, there's only 3 or 4 MIME types so I could've considered to just slap the strings in a file or enum somewhere, but as I'm writing it as a library, I wanted it to be "nice".

I don't believe I've got anything else in the pipeline, but I'm also still very heavily in the development process. I don't need a release right now as I'm working from a local repo anyway, so maybe just wait a few days just to be safe, so I don't find something tomorrow and then you have would have to cut yet another release?

**Comment by notgull** [comment]
Sounds good! I'm out and about right now so I don't have consistent access to my computer anyways. I'll cut a release in a week or so barring anything else happening.

**Comment by notgull** [comment]
Published as v0.1.1, sorry for taking so long

**Pull request merged**
